Application runs properly, but MainTest runs with error "C:\Users\xy\IdeaProjects\PreProject_2.1.4\src\test\java\MainTest.java:26:32                                                          java: incompatible types: app.model.AnimalsCage cannot be converted to app.model.Timer"